Ejemplo: 
        g++ Ejemplo.s -g -o Ejemplo
Run: 
        ./Ejemplo
gdbRun:
        gdb Ejemplo
CAuxiliar:
  as -o Ejemplo.o Ejemplo.s
  gcc -o Ejemplo Ejemplo.c Ejemplo.o
Limpiar:
        rm Ejemplo
